version: '3.2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    image: matecat-filters
    ports:
      - 8732:8732
    networks:
       - matecat-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
       - matecat-network

  amq:
    image: matecat-amq
    ports:
      - 61613:61613
      - 8161:8161
    networks:
      matecat-network:
        aliases:
          - amq

  mysql:
    image: matecat-mysql
    ports:
     - 3307:3306
    networks:
      matecat-network:
        aliases:
          - mysql

  matecat:
    image: matecat-multipurpose:2
    ## Remove this environment block if you don't need it ##
    environment:
      #XDEBUG_CONFIG: docker.for.mac.localhost
      FILTERS_ADDRESS: http://filters:8732/
      #FILTERS_ADDRESS: "https://translated-matecat-filters-v1.p.mashape.com"
      #SMTP_HOST: 10.30.1.225
      #SMTP_PORT: 2637
    ## Remove this environment block if you don't need it ##
    
    command: ["/run-matecat.sh"]

    volumes:
      - /Users/albertomassidda/matecat_local_storage:/var/www/matecat/local_storage:rw
    ports:
      - 80:80
      - 443:443
      - 7788:7788
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters

  matecat-tm-daemon:
    image: matecat-multipurpose:2
    environment:
      #XDEBUG_CONFIG: docker.for.mac.localhost
      FILTERS_ADDRESS: http://filters:8732/
      #FILTERS_ADDRESS: "https://translated-matecat-filters-v1.p.mashape.com"
      #SMTP_HOST: 10.30.1.225
      #SMTP_PORT: 2637

    command: ["/run-tm-analysis.sh"]

    volumes:
      - /Users/albertomassidda/matecat_local_storage:/var/www/matecat/local_storage:rw
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
      - matecat

  matecat-fast-daemon:
    image: matecat-multipurpose:2
    environment:
      #XDEBUG_CONFIG: docker.for.mac.localhost
      FILTERS_ADDRESS: http://filters:8732/
      #FILTERS_ADDRESS: "https://translated-matecat-filters-v1.p.mashape.com"
      #SMTP_HOST: 10.30.1.225
      #SMTP_PORT: 2637

    command: ["/run-fast-analysis.sh"]

    volumes:
      - /Users/albertomassidda/matecat_local_storage:/var/www/matecat/local_storage:rw
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
      - matecat
